# TEMPLATE: update-portfolio.yml
# Kopiere diese Datei in jedes Projekt-Repo unter .github/workflows/

name: Update Portfolio on Push

on:
  push:
    branches: [ main ]

jobs:
  trigger-portfolio-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portfolio Submodule Update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PORTFOLIO_UPDATE_TOKEN }}
          repository: MaxeLBerger/MaxeLBerger.github.io
          event-type: update-submodule
          client-payload: '{\"submodule\": \"PROJEKTNAME_HIER\"}'
          
# ANLEITUNG:
# 1. Ersetze "PROJEKTNAME_HIER" mit: AgeOfMax, FireCastle, oder AuTuneOnline
# 2. Erstelle GitHub Personal Access Token mit 'repo' scope
# 3. Füge Token als Secret im Projekt-Repo hinzu: PORTFOLIO_UPDATE_TOKEN
# 4. Commite diese Datei
# 5. Bei jedem Push triggert das automatisch das Portfolio-Update!
